### ISSUE TITLE
HelloWorld in C++

### ISSUE THREAD

**Issue by Vitaljaz** [Vitaljaz/hacktoberfest#1]
Need to create small program which prints "Hello World" in console. 
Place code to BestPractice folder.

**Comment by Abhishek07-0302** [comment]
I would like to code.

**Comment by rutuja1121** [comment]
I would like to work on this issue

**Comment by harshitsuthar77731** [comment]
i would like to code

**Comment by Vitaljaz** [comment]
Ok. Abhishek07-0302 was first.
