### ISSUE TITLE
Print Hello world in Dart

### ISSUE THREAD

**Issue by lokeshn011101** [Vitaljaz/hacktoberfest#17]
Need to create small program which prints "Hello World" in console.
Place code to BestPractice folder.

Can I get assigned for Dart?

**Comment by Vitaljaz** [comment]
@lokeshn011101 hello! Sure.

**Comment by Vitaljaz** [comment]
@lokeshn011101 don't forget to add README.md files for new folders ok?

**Comment by lokeshn011101** [comment]
> @lokeshn011101 don't forget to add README.md files for new folders ok?

Sure!

**Comment by Vitaljaz** [comment]
Done.
