### ISSUE TITLE
[BASH] Create Bash folder

### ISSUE THREAD

**Issue by Vitaljaz** [Vitaljaz/hacktoberfest#24]
Need create "Bash" folder in 2021 folder with folders: "Scripts" and "BestPractice". Don't forget add README.md files

**If you want be assigned, you must star this repository..**

**Comment by fastboot** [comment]
I'll raise a quick PR

**Comment by Vitaljaz** [comment]
@fastboot  hello! you need to star this repo.

**Comment by harshitsuthar77731** [comment]
assign me

**Comment by fastboot** [comment]
Here's the PR @Vitaljaz [PR](https://github.com/Vitaljaz/hacktoberfest/pull/26)

**Comment by Vitaljaz** [comment]
Done.
