### ISSUE TITLE
[C, C++, JavaScript, Python, Go and Others] For loop for 10 iteration.

### ISSUE THREAD

**Issue by Vitaljaz** [Vitaljaz/hacktoberfest#36]
Need to write simple for-loop with 10 iteration which prints value from 1 to 10.

**In this issue can be many assigners**
**To work with this repo - you need to star it.**

**Comment by harshitsuthar77731** [comment]
please assign me i want to do this

**Comment by harshitsuthar77731** [comment]
in c++

**Comment by sgaurav37533** [comment]
please assign me this issue for java and kotlin @Vitaljaz

**Comment by vkolova** [comment]
I want Python

**Comment by Vitaljaz** [comment]
ok. you can create new issues with if you want

**Comment by harshitsuthar77731** [comment]
where do we have to submit the code means in which directory

**Comment by Kashish-2001** [comment]
Assign this to me for C++ and Python

**Comment by sailahonkanen** [comment]
Assign this to me for javascript please

**Comment by Kashish-2001** [comment]
Assign this to me for JavaSript

**Comment by Kashish-2001** [comment]
> Assign this to me for C++ and Python
Done for C++, made a PR please check.

**Comment by Keerat666** [comment]
Assign this to me for Kotlin

**Comment by thenithinbalaji** [comment]
Assign me for Go @Vitaljaz

**Comment by avyayjain** [comment]
pls assign me this issue for python and c++

**Comment by hassanmdsifat** [comment]
Can you please assign me for C/Go/Python/JavaScript?

**Comment by smitap-31** [comment]
Please assign this to me for Scala

**Comment by Tanushreesuthar** [comment]
please assign me this in C#.

**Comment by Ritika457** [comment]
@Vitaljaz Please assign this to me.

**Comment by soumyabasuri** [comment]
@vkolova please assign this to me in python

**Comment by AnshuPathak-88825** [comment]
@Vitaljaz pls assign me this issue
