### ISSUE TITLE
[C, C++, JavaScript, Python, Go and Others] Staircase function

### ISSUE THREAD

**Issue by vkolova** [Vitaljaz/hacktoberfest#48]
Need to create Implementation of staircase function.

This is a staircase of size **_n = 4_**:
```
   #
  ##
 ###
####
```
Its base and height are both equal to **_4_**. It is drawn using # symbols and spaces. The last line is not preceded by any spaces.

Write a program that prints a staircase of size .

**Code must be placed in: 2021/[language]/Algorithms**

**In this issue can be many assigners**

**To work with this repo - you need to star it.**

**Comment by harshitsuthar77731** [comment]
i want to contribut assign me

**Comment by harshitsuthar77731** [comment]
assign me in c++

**Comment by uzzal623** [comment]
assign me in c.

**Comment by vkolova** [comment]
@Vitaljaz ? Need some help with the labels and assignments.

**Comment by 0901IT201046** [comment]
assign me in c,c++ or python

**Comment by Kashish-2001** [comment]
Assign me this to me for C++

**Comment by Kashish-2001** [comment]
Assign me in JavaScript

**Comment by Vitaljaz** [comment]
@vkolova  ty for help. done.

**Comment by Ajinkya2000** [comment]
Assign this to me for Python.

**Comment by Kashish-2001** [comment]
> Assign me this to me for C++

Done. Please check my PR.

**Comment by Kashish-2001** [comment]
> Assign me in JavaScript

Done. Please check my PR.

**Comment by nishantkumar1308** [comment]
please assign it to me.

**Comment by tchestnut85** [comment]
Hello, can you please assign me for JS?

**Comment by shadowshot-x** [comment]
Can you assign this to me for Go?

**Comment by evansusu** [comment]
Please assign this to me in C

**Comment by evansusu** [comment]
I did this in java already pls check PR @vkolova

**Comment by Kavs-123** [comment]
hey @vkolova ,
Can u pls assign this issue to me, would like to work and contribute to it ...
Thank you!

**Comment by emsewell96** [comment]
Please can you assign this to me, I would like to implement in JS :)

**Comment by vkolova** [comment]
We hit the 10 assignees limit and I can't assign any more people to this task, so I think we are done with it. I'll close it as soon as everyone's PRs have been merged.

**Comment by nishantkumar1308** [comment]
@vkolova please check my pr #174 and merge into main and Give me hacktoberfest-accepted tag.

**Comment by Ritika457** [comment]
@vkolova Please assign this to me.
