### ISSUE TITLE
HelloWorld in JavaScript

### ISSUE THREAD

**Issue by Vitaljaz** [Vitaljaz/hacktoberfest#6]
Need to create small program which prints "Hello World" in console. 
Place code to BestPractice folder.

**Comment by 1337-ishaan** [comment]
Pls assign

**Comment by MuhammadTanveer94** [comment]
@Vitaljaz could you please assign me?  i would love to to this.

**Comment by 1337-ishaan** [comment]
Completed this #7

**Comment by AmanRana10** [comment]
could you assign this to me ? @Vitaljaz

**Comment by Vitaljaz** [comment]
@1337-ishaan was first.

**Comment by 1337-ishaan** [comment]
@Vitaljaz completed this #7

**Comment by 1337-ishaan** [comment]
Does it require `hacktoberfest-accepted` label?

**Comment by Vitaljaz** [comment]
@1337-ishaan doesn't, only hacktoberfest
